version: '3'

services:
  mongors1n1:
    container_name: mongors1n1
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - "0.0.0.0:27017:27017"
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo/data1:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network
  
  mongors1n2:
    container_name: mongors1n2
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - "0.0.0.0:27027:27017"
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo/data2:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongors1n3:
    container_name: mongors1n3
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - "0.0.0.0:27037:27017"
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo/data3:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongors2n1:
    container_name: mongors2n1
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - "0.0.0.0:27047:27017"
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - ./mongo/data4:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network
  
  mongors2n2:
    container_name: mongors2n2
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
        - "0.0.0.0:27057:27017"
    expose:
        - "27017"
    environment:
        TERM: xterm
    volumes:
      - ./mongo/data5:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongors2n3:
    container_name: mongors2n3
    image: mongo:4.2.5
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
        - "0.0.0.0:27067:27017"
    expose:
        - "27017"
    environment:
        TERM: xterm
    volumes:
      - ./mongo/data6:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo/config1:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo/config2:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - ./mongo/config3:/data/db:rw
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - "0.0.0.0:27019:27017"
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - "0.0.0.0:27020:27017"
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - local_network

networks:
    local_network: